import type { ActivityEvent } from '@/lib/api';
import type { ReferralCode, FraudFlag } from '@/types';
import {
  DEFAULT_THRESHOLDS,
  type FraudThresholds,
} from './fraudDetection';

/**
 * Incremental fraud-heuristic evaluation engine.
 *
 * Keeps per-wallet rolling state and aggregates so that each scheduled or
 * on-demand run only processes new events after the last checkpointed ledger,
 * updates aggregates for wallets that had activity, and evaluates heuristics
 * only for those changed wallets.
 *
 * Designed to be pure and deterministic: given the same sequence of events,
 * incremental evaluation produces flags identical to full evaluation over
 * the entire historical window.
 */

export interface WalletReferralAggregate {
  selfRedemptions: Array<{ code: string; createdAt: number; usedAt: number }>;
  // Codes generated by this wallet (scout)
  scoutCodes: Record<
    string,
    {
      code: string;
      createdAt: number;
      usedAt: number | null;
      usedBy: string | null;
    }
  >;
  // Codes redeemed by this wallet (redeemer)
  redeemedCodes: Record<
    string,
    {
      code: string;
      scoutWallet: string;
      usedAt: number;
    }
  >;
}

export interface WalletPayToContactAggregate {
  // Contact timestamps (ms)
  contactTimestamps: number[];
  // Subscription timestamps (ms)
  subscriptionTimestamps: number[];
  // Rolling hour bucket counts (e.g. '2024-01-01T12' -> count)
  contactsPerHour: Record<string, number>;
}

export interface WalletFraudAggregate {
  wallet: string;
  referral: WalletReferralAggregate;
  payToContact: WalletPayToContactAggregate;
  updatedAt: number;
}

export interface IncrementalFraudState {
  wallets: Map<string, WalletFraudAggregate>;
  activeFlags: Map<string, FraudFlag[]>; // keyed by wallet
  lastLedger: number;
  lastEventId: string | null;
  updatedAt: number;
}

export function createEmptyWalletAggregate(wallet: string): WalletFraudAggregate {
  return {
    wallet,
    referral: {
      selfRedemptions: [],
      scoutCodes: {},
      redeemedCodes: {},
    },
    payToContact: {
      contactTimestamps: [],
      subscriptionTimestamps: [],
      contactsPerHour: {},
    },
    updatedAt: Date.now(),
  };
}

export function createInitialIncrementalState(): IncrementalFraudState {
  return {
    wallets: new Map(),
    activeFlags: new Map(),
    lastLedger: 0,
    lastEventId: null,
    updatedAt: Date.now(),
  };
}

function makeFlag(
  category: FraudFlag['category'],
  heuristic: string,
  wallets: string[],
  severity: FraudFlag['severity'],
  reason: string,
  evidence: FraudFlag['evidence'],
): FraudFlag {
  return {
    id: `${category}:${heuristic}:${wallets.join(',')}`,
    category,
    heuristic,
    severity,
    wallets,
    reason,
    evidence,
  };
}

function getOrCreateWallet(
  state: IncrementalFraudState,
  wallet: string,
): WalletFraudAggregate {
  let agg = state.wallets.get(wallet);
  if (!agg) {
    agg = createEmptyWalletAggregate(wallet);
    state.wallets.set(wallet, agg);
  }
  return agg;
}

function formatHourBucket(timestampMs: number): string {
  const d = new Date(timestampMs);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}T${String(d.getUTCHours()).padStart(2, '0')}`;
}

/**
 * Ingests a referral code into the incremental state.
 * Returns the wallets whose aggregates were modified.
 */
export function applyReferralCode(
  state: IncrementalFraudState,
  code: ReferralCode,
): string[] {
  const changed: string[] = [];
  const scoutWallet = code.scoutWallet;
  if (!scoutWallet) return changed;

  const scoutAgg = getOrCreateWallet(state, scoutWallet);
  const existingCode = scoutAgg.referral.scoutCodes[code.code];
  const isNew = !existingCode;
  const isUpdated =
    existingCode &&
    (existingCode.usedBy !== code.usedBy || existingCode.usedAt !== code.usedAt);

  if (isNew || isUpdated) {
    scoutAgg.referral.scoutCodes[code.code] = {
      code: code.code,
      createdAt: code.createdAt,
      usedAt: code.usedAt,
      usedBy: code.usedBy,
    };
    scoutAgg.updatedAt = Date.now();
    changed.push(scoutWallet);

    // Self-redemption check
    if (code.usedBy && code.usedBy === scoutWallet) {
      if (!scoutAgg.referral.selfRedemptions.some((s) => s.code === code.code)) {
        scoutAgg.referral.selfRedemptions.push({
          code: code.code,
          createdAt: code.createdAt,
          usedAt: code.usedAt ?? code.createdAt,
        });
      }
    }
  }

  // If redeemed by someone else, track on redeemer's aggregate
  if (code.usedBy && code.usedBy !== scoutWallet) {
    const redeemerAgg = getOrCreateWallet(state, code.usedBy);
    const existingRedeemed = redeemerAgg.referral.redeemedCodes[code.code];
    if (!existingRedeemed) {
      redeemerAgg.referral.redeemedCodes[code.code] = {
        code: code.code,
        scoutWallet,
        usedAt: code.usedAt ?? code.createdAt,
      };
      redeemerAgg.updatedAt = Date.now();
      changed.push(code.usedBy);
    }
  }

  return changed;
}

/**
 * Ingests an activity event into the incremental state.
 * Returns the wallets whose aggregates were modified.
 */
export function applyActivityEvent(
  state: IncrementalFraudState,
  event: ActivityEvent,
): string[] {
  const actor = event.actor;
  if (!actor) return [];

  const timestampMs = event.timestamp * 1000;
  const agg = getOrCreateWallet(state, actor);
  let changed = false;

  if (event.type === 'player_contacted') {
    agg.payToContact.contactTimestamps.push(timestampMs);
    const hourBucket = formatHourBucket(timestampMs);
    agg.payToContact.contactsPerHour[hourBucket] =
      (agg.payToContact.contactsPerHour[hourBucket] ?? 0) + 1;
    changed = true;
  } else if (event.type === 'scout_subscribed') {
    agg.payToContact.subscriptionTimestamps.push(timestampMs);
    changed = true;
  }

  if (changed) {
    agg.updatedAt = Date.now();
    return [actor];
  }
  return [];
}

/**
 * Evaluates all 6 heuristics for a single wallet against its aggregated data.
 */
export function evaluateRulesForWallet(
  state: IncrementalFraudState,
  wallet: string,
  t: FraudThresholds = DEFAULT_THRESHOLDS,
): FraudFlag[] {
  const agg = state.wallets.get(wallet);
  if (!agg) return [];

  const flags: FraudFlag[] = [];

  // 1) Self-redemption
  for (const s of agg.referral.selfRedemptions) {
    flags.push(
      makeFlag(
        'referral',
        'self_redemption',
        [wallet],
        'high',
        `Code ${s.code} was generated and redeemed by the same wallet.`,
        { code: s.code, scoutWallet: wallet },
      ),
    );
  }

  // 2) Fast redemption pattern (wallet as scout)
  const scoutCodesList = Object.values(agg.referral.scoutCodes);
  const redeemed = scoutCodesList.filter(
    (c): c is { code: string; createdAt: number; usedAt: number; usedBy: string } =>
      c.usedBy !== null && c.usedAt !== null,
  );
  if (redeemed.length >= t.MIN_REDEMPTIONS_FOR_SPEED_CHECK) {
    const fast = redeemed.filter(
      (c) => c.usedAt - c.createdAt <= t.FAST_REDEMPTION_MS,
    );
    const ratio = fast.length / redeemed.length;
    if (ratio >= t.FAST_REDEMPTION_RATIO_THRESHOLD) {
      flags.push(
        makeFlag(
          'referral',
          'fast_redemption_pattern',
          [wallet],
          ratio >= 0.9 ? 'high' : 'medium',
          `${fast.length} of ${redeemed.length} redemptions happened within ${t.FAST_REDEMPTION_MS / 1000}s of code generation.`,
          {
            redemptions: redeemed.length,
            fastRedemptions: fast.length,
            ratio: Number(ratio.toFixed(2)),
          },
        ),
      );
    }
  }

  // 3) Concentrated redeemer (wallet as scout)
  const allRedeemedScoutCodes = scoutCodesList.filter((c) => c.usedBy !== null);
  if (allRedeemedScoutCodes.length >= t.MIN_REDEMPTIONS_FOR_CONCENTRATION_CHECK) {
    const countByRedeemer: Record<string, number> = {};
    for (const c of allRedeemedScoutCodes) {
      const r = c.usedBy!;
      countByRedeemer[r] = (countByRedeemer[r] ?? 0) + 1;
    }
    let topRedeemer = '';
    let topCount = 0;
    for (const [r, count] of Object.entries(countByRedeemer)) {
      if (count > topCount) {
        topCount = count;
        topRedeemer = r;
      }
    }
    const ratio = topCount / allRedeemedScoutCodes.length;
    if (ratio >= t.CONCENTRATION_RATIO_THRESHOLD) {
      flags.push(
        makeFlag(
          'referral',
          'concentrated_redeemer',
          [wallet, topRedeemer],
          ratio >= 0.8 ? 'high' : 'medium',
          `${topCount} of ${allRedeemedScoutCodes.length} of this scout's redemptions came from a single wallet.`,
          {
            redemptions: allRedeemedScoutCodes.length,
            topRedeemerRedemptions: topCount,
            distinctRedeemers: Object.keys(countByRedeemer).length,
            ratio: Number(ratio.toFixed(2)),
          },
        ),
      );
    }
  }

  // 4) Cross-scout redeemer ring (wallet as redeemer)
  const redeemedAsUser = Object.values(agg.referral.redeemedCodes);
  const distinctScouts = new Set(redeemedAsUser.map((c) => c.scoutWallet));
  if (distinctScouts.size >= t.RING_MIN_DISTINCT_SCOUTS) {
    flags.push(
      makeFlag(
        'referral',
        'cross_scout_redeemer_ring',
        [wallet, ...distinctScouts],
        distinctScouts.size >= t.RING_MIN_DISTINCT_SCOUTS * 2 ? 'high' : 'medium',
        `Wallet redeemed referral codes from ${distinctScouts.size} distinct scouts.`,
        {
          distinctScouts: distinctScouts.size,
          totalRedemptions: redeemedAsUser.length,
        },
      ),
    );
  }

  // 5) Rapid contact burst (wallet as scout)
  const contactTimestamps = [...agg.payToContact.contactTimestamps].sort(
    (a, b) => a - b,
  );
  if (contactTimestamps.length >= t.CONTACT_BURST_MIN_COUNT) {
    let maxInWindow = 1;
    let windowStart = 0;
    for (let i = 0; i < contactTimestamps.length; i++) {
      while (
        contactTimestamps[i] - contactTimestamps[windowStart] >
        t.CONTACT_BURST_WINDOW_MS
      ) {
        windowStart++;
      }
      maxInWindow = Math.max(maxInWindow, i - windowStart + 1);
    }
    if (maxInWindow >= t.CONTACT_BURST_MIN_COUNT) {
      flags.push(
        makeFlag(
          'pay_to_contact',
          'rapid_contact_burst',
          [wallet],
          maxInWindow >= t.CONTACT_BURST_MIN_COUNT * 2 ? 'high' : 'medium',
          `${maxInWindow} pay-to-contact calls within ${t.CONTACT_BURST_WINDOW_MS / 60000} minutes.`,
          {
            maxInWindow,
            windowMinutes: t.CONTACT_BURST_WINDOW_MS / 60000,
            totalContacts: contactTimestamps.length,
          },
        ),
      );
    }
  }

  // 6) Subscription cycling (wallet as scout)
  const subscriptionTimestamps = [
    ...agg.payToContact.subscriptionTimestamps,
  ].sort((a, b) => a - b);
  if (subscriptionTimestamps.length >= t.MIN_SUBSCRIPTIONS_FOR_CYCLING_CHECK) {
    const totalContacts = contactTimestamps.length;
    const avgContactsPerSubscription =
      totalContacts / subscriptionTimestamps.length;
    if (avgContactsPerSubscription <= t.CYCLING_MAX_CONTACTS_PER_SUBSCRIPTION) {
      const gaps = subscriptionTimestamps
        .slice(1)
        .map((ts, idx) => ts - subscriptionTimestamps[idx]);
      const avgGapMs =
        gaps.length > 0 ? gaps.reduce((a, b) => a + b, 0) / gaps.length : 0;
      const severity =
        avgContactsPerSubscription <= 1 && subscriptionTimestamps.length >= 5
          ? 'high'
          : 'medium';

      flags.push(
        makeFlag(
          'pay_to_contact',
          'subscription_cycling',
          [wallet],
          severity,
          `${subscriptionTimestamps.length} subscriptions averaging ${avgContactsPerSubscription.toFixed(1)} contacts each.`,
          {
            subscriptions: subscriptionTimestamps.length,
            totalContacts,
            avgContactsPerSubscription: Number(
              avgContactsPerSubscription.toFixed(2),
            ),
            avgGapDays: Number((avgGapMs / 86_400_000).toFixed(1)),
          },
        ),
      );
    }
  }

  return flags;
}

/**
 * Re-evaluates rules only for the changed wallets, updates the active flags map,
 * and returns the full sorted list of active flags across all wallets.
 */
export function updateActiveFlagsForChangedWallets(
  state: IncrementalFraudState,
  changedWallets: Iterable<string>,
  thresholds: FraudThresholds = DEFAULT_THRESHOLDS,
): FraudFlag[] {
  for (const wallet of changedWallets) {
    const flags = evaluateRulesForWallet(state, wallet, thresholds);
    if (flags.length > 0) {
      state.activeFlags.set(wallet, flags);
    } else {
      state.activeFlags.delete(wallet);
    }
  }

  // Collect all active flags across the entire state
  const allFlags: FraudFlag[] = [];
  for (const flags of state.activeFlags.values()) {
    allFlags.push(...flags);
  }

  // Sort by severity rank, matching lib/fraudDetection.ts
  const severityRank = { high: 0, medium: 1, low: 2 } as const;
  allFlags.sort((a, b) => severityRank[a.severity] - severityRank[b.severity]);

  return allFlags;
}

export interface IncrementalStepResult {
  flags: FraudFlag[];
  changedWallets: string[];
  eventsProcessed: number;
  durationMs: number;
  hitTimeBudget: boolean;
  lastLedger: number;
}

/**
 * Processes a batch of referral codes and activity events incrementally,
 * updating only the affected wallets and respecting an optional time budget.
 */
export function runIncrementalStep(
  state: IncrementalFraudState,
  referralCodes: ReferralCode[],
  activityEvents: ActivityEvent[],
  options: {
    thresholds?: FraudThresholds;
    timeBudgetMs?: number;
    startTimeMs?: number;
    safetyMarginMs?: number;
  } = {},
): IncrementalStepResult {
  const startTime = options.startTimeMs ?? Date.now();
  const timeBudget = options.timeBudgetMs ?? Infinity;
  const safetyMargin = options.safetyMarginMs ?? 0;
  const thresholds = options.thresholds ?? DEFAULT_THRESHOLDS;

  const changedWallets = new Set<string>();
  let eventsProcessed = 0;
  let hitTimeBudget = false;

  // Process referral codes
  for (const code of referralCodes) {
    if (Date.now() - startTime >= timeBudget - safetyMargin) {
      hitTimeBudget = true;
      break;
    }
    const modified = applyReferralCode(state, code);
    for (const w of modified) changedWallets.add(w);
    eventsProcessed++;
  }

  // Process activity events if time allows
  if (!hitTimeBudget) {
    for (const event of activityEvents) {
      if (Date.now() - startTime >= timeBudget - safetyMargin) {
        hitTimeBudget = true;
        break;
      }
      const modified = applyActivityEvent(state, event);
      for (const w of modified) changedWallets.add(w);
      if (event.ledger !== undefined && event.ledger > state.lastLedger) {
        state.lastLedger = event.ledger;
      }
      state.lastEventId = event.id;
      eventsProcessed++;
    }
  }

  // Evaluate rules only for wallets that changed
  const flags = updateActiveFlagsForChangedWallets(
    state,
    changedWallets,
    thresholds,
  );

  state.updatedAt = Date.now();
  const durationMs = Date.now() - startTime;

  return {
    flags,
    changedWallets: Array.from(changedWallets),
    eventsProcessed,
    durationMs,
    hitTimeBudget,
    lastLedger: state.lastLedger,
  };
}
