'use client';
import { useEffect, useState } from 'react';
import { useToast } from '@/components/ui/Toast';
import EmptyState from '@/components/ui/EmptyState';
import TruncatedAddress from '@/components/ui/TruncatedAddress';
import { getReferralOverview } from '@/lib/api';
import type { ReferralOverview } from '@/types';

/** /admin/referrals — referral program totals and top referrers. */
export default function AdminReferralsPage() {
  const { show } = useToast();
  const [referralOverview, setReferralOverview] =
    useState<ReferralOverview | null>(null);
  const [referralLoading, setReferralLoading] = useState(false);

  useEffect(() => {
    setReferralLoading(true);
    getReferralOverview()
      .then(setReferralOverview)
      .catch(() =>
        show({
          message: 'Failed to load referral program data.',
          variant: 'error',
        }),
      )
      .finally(() => setReferralLoading(false));
  }, [show]);

  return (
    <div className="max-w-3xl flex flex-col gap-8">
      <h1 className="text-3xl font-bold text-white">Referrals</h1>

      <section className="bg-brand-card border border-gray-800 rounded-xl p-6 flex flex-col gap-4">
        <h2 className="text-lg font-semibold text-white">Referral Program</h2>
        {referralLoading ? (
          <p className="text-sm text-gray-400">Loading…</p>
        ) : !referralOverview || referralOverview.totalCodes === 0 ? (
          <EmptyState
            title="No referral activity yet"
            description="Codes and successful referrals generated by scouts will appear here."
          />
        ) : (
          <>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-xs uppercase tracking-wide text-gray-400">
                  Codes Generated
                </p>
                <p className="text-2xl font-semibold text-white">
                  {referralOverview.totalCodes}
                </p>
              </div>
              <div>
                <p className="text-xs uppercase tracking-wide text-gray-400">
                  Successful Referrals
                </p>
                <p className="text-2xl font-semibold text-white">
                  {referralOverview.totalSuccessfulReferrals}
                </p>
              </div>
            </div>

            <div>
              <h3 className="text-sm font-semibold text-gray-300 mb-2">
                Top Referrers
              </h3>
              <ul className="flex flex-col divide-y divide-gray-800">
                {referralOverview.topReferrers.map((r) => (
                  <li
                    key={r.scoutWallet}
                    className="flex items-center justify-between gap-4 py-2 text-sm"
                  >
                    <span className="font-mono text-gray-300 truncate">
                      <TruncatedAddress
                        address={r.scoutWallet}
                        className="text-gray-300"
                      />
                    </span>
                    <span className="text-gray-400 shrink-0">
                      {r.successfulReferrals} referral
                      {r.successfulReferrals !== 1 ? 's' : ''} · {r.totalCodes}{' '}
                      code{r.totalCodes !== 1 ? 's' : ''}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </>
        )}
      </section>
    </div>
  );
}
