import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import PlayerVitalsCard from '@/components/player/PlayerVitalsCard';
import type { PlayerVitals } from '@/types';

function makeVitals(overrides: Partial<PlayerVitals> = {}): PlayerVitals {
  return {
    name: 'Ada Lovelace',
    age: 21,
    position: 'ST',
    region: 'NG',
    nationality: 'Nigerian',
    ...overrides,
  };
}

describe('PlayerVitalsCard', () => {
  it('renders the player name as the section heading (h2 by default)', () => {
    render(<PlayerVitalsCard vitals={makeVitals()} progressLevel={2} />);
    expect(
      screen.getByRole('heading', { name: 'Ada Lovelace', level: 2 }),
    ).toBeInTheDocument();
  });

  it('renders the position and region joined by a middle-dot separator', () => {
    render(
      <PlayerVitalsCard
        vitals={makeVitals({ position: 'ST', region: 'NG' })}
        progressLevel={2}
      />,
    );
    // Regex matcher over a single literal string: the subtitle renders
    // position + ' · ' + region as three separate React text children
    // inside <p>, and `getByText('ST · NG')` does not always coalesce
    // them across sibling text nodes. The regex preserves the test's
    // intent (both values present, separator between them) without
    // coupling to internal text-node boundaries.
    expect(screen.getByText(/ST\s*·\s*NG/)).toBeInTheDocument();
  });

  it('passes progressLevel through to ProgressBar’s aria-valuenow', () => {
    render(
      <PlayerVitalsCard vitals={makeVitals()} progressLevel={3} />,
    );
    // ProgressBar exposes role="progressbar" with aria-valuenow=level. The
    // exact label changes per level (PROGRESS_LABELS in @/types), but the
    // numeric aria-valuenow is the data we want to lock in for the
    // pass-through contract from PlayerVitalsCard.
    const bar = screen.getByRole('progressbar');
    expect(bar).toHaveAttribute('aria-valuenow', '3');
    expect(bar).toHaveAttribute('aria-valuemin', '0');
    expect(bar).toHaveAttribute('aria-valuemax', '3');
  });

  it('renders a different aria-valuenow when progressLevel changes', () => {
    const { rerender } = render(
      <PlayerVitalsCard vitals={makeVitals()} progressLevel={0} />,
    );
    expect(screen.getByRole('progressbar')).toHaveAttribute(
      'aria-valuenow',
      '0',
    );

    rerender(
      <PlayerVitalsCard vitals={makeVitals()} progressLevel={1} />,
    );
    expect(screen.getByRole('progressbar')).toHaveAttribute(
      'aria-valuenow',
      '1',
    );
  });

  it('renders name/position/region values containing HTML-unsafe characters as literal text', () => {
    // Smoke test: values come through React’s text encoder. A raw
    // <script> in props must end up as literal text — not parsed as
    // markup. Guards against future regressions that might switch to
    // dangerouslySetInnerHTML.
    const vitals = makeVitals({
      name: '<img src=x onerror=alert(1)>',
      position: '<script>position</script>',
      region: '<iframe>region</iframe>',
    });

    const { container } = render(
      <PlayerVitalsCard vitals={vitals} progressLevel={2} />,
    );

    expect(
      screen.getByRole('heading', {
        name: '<img src=x onerror=alert(1)>',
        level: 2,
      }),
    ).toBeInTheDocument();
    // Assert the load-bearing safety property directly via DOM: no
    // <script> or <iframe> child of the subtitle <p> was created from
    // the position / region props. The headline value still surfaces as
    // literal text through React's text encoder. Query selectors are
    // scoped to `p` so unrelated top-level script / iframe elements later
    // in the tree cannot produce a false pass.
    expect(container.querySelector('p script')).toBeNull();
    expect(container.querySelector('p iframe')).toBeNull();
  });

  it('exposes the section as a navigable region via aria-labelledby + heading id', () => {
    render(<PlayerVitalsCard vitals={makeVitals()} progressLevel={2} />);

    // The h2 carries an instance-unique id (per useId). The exact value
    // is generated by React and is not part of the public contract, so
    // we pin the load-bearing property: aria-labelledby on the section
    // matches the heading id and the region role resolves via the
    // accessibility tree.
    const heading = screen.getByRole('heading', {
      name: 'Ada Lovelace',
      level: 2,
    });
    const headingId = heading.getAttribute('id');
    expect(headingId).toBeTruthy();
    expect(headingId).toMatch(/^vitals-heading-/);
    expect(headingId).not.toBe('vitals-heading');

    const section = heading.closest('section');
    expect(section).not.toBeNull();
    expect(section).toHaveAttribute('aria-labelledby', headingId!);

    // The section's accessible name comes from the label-referenced
    // heading text — the player's vitals.name — so
    // getByRole('region', { name: ... }) resolves it.
    expect(
      screen.getByRole('region', { name: 'Ada Lovelace' }),
    ).toBeInTheDocument();
  });

  it('generates a unique heading id per instance (no collision when many cards render)', () => {
    render(
      <>
        <PlayerVitalsCard vitals={makeVitals({ name: 'Ada' })} progressLevel={2} />
        <PlayerVitalsCard vitals={makeVitals({ name: 'Ada' })} progressLevel={2} />
      </>,
    );

    const headings = screen.getAllByRole('heading', { name: 'Ada', level: 2 });
    expect(headings).toHaveLength(2);
    const ids = headings.map((h) => h.getAttribute('id'));
    expect(new Set(ids).size).toBe(2);
    ids.forEach((id) => {
      expect(id).toMatch(/^vitals-heading-/);
    });
  });

  it('renders h3 instead of h2 when headingLevel=3 is passed', () => {
    render(
      <PlayerVitalsCard
        vitals={makeVitals()}
        progressLevel={2}
        headingLevel={3}
      />,
    );
    expect(
      screen.getByRole('heading', { name: 'Ada Lovelace', level: 3 }),
    ).toBeInTheDocument();
    expect(
      screen.queryByRole('heading', { name: 'Ada Lovelace', level: 2 }),
    ).not.toBeInTheDocument();
  });

  it('omits the section landmark when landmark=false', () => {
    const { container } = render(
      <PlayerVitalsCard
        vitals={makeVitals()}
        progressLevel={2}
        landmark={false}
      />,
    );
    expect(container.querySelector('section')).toBeNull();
    // The heading still carries the per-instance id (useful for tests
    // and deep links) but the section's aria-labelledby is gone, so the
    // heading should not be reachable via getByRole('region', ...).
    expect(
      screen.queryByRole('region', { name: 'Ada Lovelace' }),
    ).not.toBeInTheDocument();
  });

  it('omits the bg-brand-card visual chrome when chrome=false', () => {
    const { container } = render(
      <PlayerVitalsCard
        vitals={makeVitals()}
        progressLevel={2}
        chrome={false}
      />,
    );
    // The section is kept (landmark defaults to true), but no inner
    // bg-brand-card div wraps the content.
    const section = container.querySelector('section');
    expect(section).not.toBeNull();
    const chromeDiv = section?.querySelector('.bg-brand-card');
    expect(chromeDiv).toBeNull();
  });

  it('renders plain content (no section landmark, no chrome) when both are false', () => {
    const { container } = render(
      <PlayerVitalsCard
        vitals={makeVitals()}
        progressLevel={2}
        landmark={false}
        chrome={false}
      />,
    );
    expect(container.querySelector('section')).toBeNull();
    expect(container.querySelector('.bg-brand-card')).toBeNull();
    // The four info pieces still render: heading, subtitle paragraph,
    // ProgressBar role.
    expect(
      screen.getByRole('heading', { name: 'Ada Lovelace', level: 2 }),
    ).toBeInTheDocument();
    expect(screen.getByText(/ST\s*·\s*NG/)).toBeInTheDocument();
    expect(screen.getByRole('progressbar')).toBeInTheDocument();
  });
});
