name: Link Checker

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.10.0
        with:
          args: "--no-progress --exclude 'mailto|github.com/.*#' README.md DEVELOPMENT.md DEPLOYMENT.md CONTRIBUTING.md packages/indexer/README.md"
          # The workflow will fail if any broken links are found.
